[package]
name = "sentry-example"
version = "0.1.0"
authors = ["Adam"]
edition = "2018"

[dependencies]
actix-web = "0.7.19"
failure = "0.1.8"
lazy_static = "1.4.0"
pretty_env_logger = "0.4"
sentry = { version = "0.19.0", features = ["debug-logs"] }
sentry-actix = "0.19.0"
serde = "1.0.114"
